package test.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import test.entity.DepartmentEntity;
import test.entity.DepartmentEntityExample;

public interface DepartmentEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depterment
     *
     * @mbg.generated Wed Mar 20 10:05:57 CST 2019
     */
    long countByExample(DepartmentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depterment
     *
     * @mbg.generated Wed Mar 20 10:05:57 CST 2019
     */
    int deleteByExample(DepartmentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depterment
     *
     * @mbg.generated Wed Mar 20 10:05:57 CST 2019
     */
    int deleteByPrimaryKey(String dept_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depterment
     *
     * @mbg.generated Wed Mar 20 10:05:57 CST 2019
     */
    int insert(DepartmentEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depterment
     *
     * @mbg.generated Wed Mar 20 10:05:57 CST 2019
     */
    int insertSelective(DepartmentEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depterment
     *
     * @mbg.generated Wed Mar 20 10:05:57 CST 2019
     */
    List<DepartmentEntity> selectByExample(DepartmentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depterment
     *
     * @mbg.generated Wed Mar 20 10:05:57 CST 2019
     */
    DepartmentEntity selectByPrimaryKey(String dept_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depterment
     *
     * @mbg.generated Wed Mar 20 10:05:57 CST 2019
     */
    int updateByExampleSelective(@Param("record") DepartmentEntity record, @Param("example") DepartmentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depterment
     *
     * @mbg.generated Wed Mar 20 10:05:57 CST 2019
     */
    int updateByExample(@Param("record") DepartmentEntity record, @Param("example") DepartmentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depterment
     *
     * @mbg.generated Wed Mar 20 10:05:57 CST 2019
     */
    int updateByPrimaryKeySelective(DepartmentEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depterment
     *
     * @mbg.generated Wed Mar 20 10:05:57 CST 2019
     */
    int updateByPrimaryKey(DepartmentEntity record);
}