package test.entity;

import java.util.ArrayList;
import java.util.List;

public class DepartmentEntityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table depterment
     *
     * @mbg.generated Wed Mar 20 10:05:57 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table depterment
     *
     * @mbg.generated Wed Mar 20 10:05:57 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table depterment
     *
     * @mbg.generated Wed Mar 20 10:05:57 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depterment
     *
     * @mbg.generated Wed Mar 20 10:05:57 CST 2019
     */
    public DepartmentEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depterment
     *
     * @mbg.generated Wed Mar 20 10:05:57 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depterment
     *
     * @mbg.generated Wed Mar 20 10:05:57 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depterment
     *
     * @mbg.generated Wed Mar 20 10:05:57 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depterment
     *
     * @mbg.generated Wed Mar 20 10:05:57 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depterment
     *
     * @mbg.generated Wed Mar 20 10:05:57 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depterment
     *
     * @mbg.generated Wed Mar 20 10:05:57 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depterment
     *
     * @mbg.generated Wed Mar 20 10:05:57 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depterment
     *
     * @mbg.generated Wed Mar 20 10:05:57 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depterment
     *
     * @mbg.generated Wed Mar 20 10:05:57 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depterment
     *
     * @mbg.generated Wed Mar 20 10:05:57 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table depterment
     *
     * @mbg.generated Wed Mar 20 10:05:57 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDept_idIsNull() {
            addCriterion("dept_id is null");
            return (Criteria) this;
        }

        public Criteria andDept_idIsNotNull() {
            addCriterion("dept_id is not null");
            return (Criteria) this;
        }

        public Criteria andDept_idEqualTo(String value) {
            addCriterion("dept_id =", value, "dept_id");
            return (Criteria) this;
        }

        public Criteria andDept_idNotEqualTo(String value) {
            addCriterion("dept_id <>", value, "dept_id");
            return (Criteria) this;
        }

        public Criteria andDept_idGreaterThan(String value) {
            addCriterion("dept_id >", value, "dept_id");
            return (Criteria) this;
        }

        public Criteria andDept_idGreaterThanOrEqualTo(String value) {
            addCriterion("dept_id >=", value, "dept_id");
            return (Criteria) this;
        }

        public Criteria andDept_idLessThan(String value) {
            addCriterion("dept_id <", value, "dept_id");
            return (Criteria) this;
        }

        public Criteria andDept_idLessThanOrEqualTo(String value) {
            addCriterion("dept_id <=", value, "dept_id");
            return (Criteria) this;
        }

        public Criteria andDept_idLike(String value) {
            addCriterion("dept_id like", value, "dept_id");
            return (Criteria) this;
        }

        public Criteria andDept_idNotLike(String value) {
            addCriterion("dept_id not like", value, "dept_id");
            return (Criteria) this;
        }

        public Criteria andDept_idIn(List<String> values) {
            addCriterion("dept_id in", values, "dept_id");
            return (Criteria) this;
        }

        public Criteria andDept_idNotIn(List<String> values) {
            addCriterion("dept_id not in", values, "dept_id");
            return (Criteria) this;
        }

        public Criteria andDept_idBetween(String value1, String value2) {
            addCriterion("dept_id between", value1, value2, "dept_id");
            return (Criteria) this;
        }

        public Criteria andDept_idNotBetween(String value1, String value2) {
            addCriterion("dept_id not between", value1, value2, "dept_id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("dept_name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("dept_name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("dept_name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("dept_name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("dept_name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("dept_name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("dept_name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("dept_name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("dept_name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("dept_name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("dept_name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("dept_name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("dept_name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("dept_name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andDept_addrIsNull() {
            addCriterion("dept_addr is null");
            return (Criteria) this;
        }

        public Criteria andDept_addrIsNotNull() {
            addCriterion("dept_addr is not null");
            return (Criteria) this;
        }

        public Criteria andDept_addrEqualTo(String value) {
            addCriterion("dept_addr =", value, "dept_addr");
            return (Criteria) this;
        }

        public Criteria andDept_addrNotEqualTo(String value) {
            addCriterion("dept_addr <>", value, "dept_addr");
            return (Criteria) this;
        }

        public Criteria andDept_addrGreaterThan(String value) {
            addCriterion("dept_addr >", value, "dept_addr");
            return (Criteria) this;
        }

        public Criteria andDept_addrGreaterThanOrEqualTo(String value) {
            addCriterion("dept_addr >=", value, "dept_addr");
            return (Criteria) this;
        }

        public Criteria andDept_addrLessThan(String value) {
            addCriterion("dept_addr <", value, "dept_addr");
            return (Criteria) this;
        }

        public Criteria andDept_addrLessThanOrEqualTo(String value) {
            addCriterion("dept_addr <=", value, "dept_addr");
            return (Criteria) this;
        }

        public Criteria andDept_addrLike(String value) {
            addCriterion("dept_addr like", value, "dept_addr");
            return (Criteria) this;
        }

        public Criteria andDept_addrNotLike(String value) {
            addCriterion("dept_addr not like", value, "dept_addr");
            return (Criteria) this;
        }

        public Criteria andDept_addrIn(List<String> values) {
            addCriterion("dept_addr in", values, "dept_addr");
            return (Criteria) this;
        }

        public Criteria andDept_addrNotIn(List<String> values) {
            addCriterion("dept_addr not in", values, "dept_addr");
            return (Criteria) this;
        }

        public Criteria andDept_addrBetween(String value1, String value2) {
            addCriterion("dept_addr between", value1, value2, "dept_addr");
            return (Criteria) this;
        }

        public Criteria andDept_addrNotBetween(String value1, String value2) {
            addCriterion("dept_addr not between", value1, value2, "dept_addr");
            return (Criteria) this;
        }

        public Criteria andDept_typeIsNull() {
            addCriterion("dept_type is null");
            return (Criteria) this;
        }

        public Criteria andDept_typeIsNotNull() {
            addCriterion("dept_type is not null");
            return (Criteria) this;
        }

        public Criteria andDept_typeEqualTo(String value) {
            addCriterion("dept_type =", value, "dept_type");
            return (Criteria) this;
        }

        public Criteria andDept_typeNotEqualTo(String value) {
            addCriterion("dept_type <>", value, "dept_type");
            return (Criteria) this;
        }

        public Criteria andDept_typeGreaterThan(String value) {
            addCriterion("dept_type >", value, "dept_type");
            return (Criteria) this;
        }

        public Criteria andDept_typeGreaterThanOrEqualTo(String value) {
            addCriterion("dept_type >=", value, "dept_type");
            return (Criteria) this;
        }

        public Criteria andDept_typeLessThan(String value) {
            addCriterion("dept_type <", value, "dept_type");
            return (Criteria) this;
        }

        public Criteria andDept_typeLessThanOrEqualTo(String value) {
            addCriterion("dept_type <=", value, "dept_type");
            return (Criteria) this;
        }

        public Criteria andDept_typeLike(String value) {
            addCriterion("dept_type like", value, "dept_type");
            return (Criteria) this;
        }

        public Criteria andDept_typeNotLike(String value) {
            addCriterion("dept_type not like", value, "dept_type");
            return (Criteria) this;
        }

        public Criteria andDept_typeIn(List<String> values) {
            addCriterion("dept_type in", values, "dept_type");
            return (Criteria) this;
        }

        public Criteria andDept_typeNotIn(List<String> values) {
            addCriterion("dept_type not in", values, "dept_type");
            return (Criteria) this;
        }

        public Criteria andDept_typeBetween(String value1, String value2) {
            addCriterion("dept_type between", value1, value2, "dept_type");
            return (Criteria) this;
        }

        public Criteria andDept_typeNotBetween(String value1, String value2) {
            addCriterion("dept_type not between", value1, value2, "dept_type");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table depterment
     *
     * @mbg.generated do_not_delete_during_merge Wed Mar 20 10:05:57 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table depterment
     *
     * @mbg.generated Wed Mar 20 10:05:57 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}